apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-workflows
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: '60'
spec:
  project: gitops-apps
  destination:
    server: https://kubernetes.default.svc
    namespace: argo
  ignoreDifferences:
  - group: external-secrets.io
    kind: ExternalSecret
    jsonPointers:
    - "/spec/target/deletionPolicy"
    - "/spec/data/0/remoteRef/conversionStrategy"
    - "/spec/data/0/remoteRef/decodingStrategy"
    - "/spec/data/0/remoteRef/metadataPolicy"
    - "/spec/data/0/remoteRef/nullBytePolicy"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
    - SkipDryRunOnMissingResource=true
  sources:
  - repoURL: harbor.api-api-api.com/helm-charts
    chart: common-app
    targetRevision: 0.1.0
    helm:
      releaseName: argo-workflows
      valueFiles:
      - "$values/values/argo-workflows.yaml"
  - repoURL: https://github.com/anomaly51/utility-k3s-argocd.git
    targetRevision: main
    ref: values
