apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kibana
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: '57'
spec:
  project: gitops-apps
  source:
    repoURL: https://helm.elastic.co
    chart: kibana
    targetRevision: 8.5.1
    helm:
      releaseName: kibana
      values: |
        replicas: 1
        elasticsearchHosts: http://elasticsearch-master:9200
        healthCheckPath: "/api/status"
        resources:
          requests:
            cpu: 100m
            memory: 512Mi
          limits:
            memory: 1Gi
  destination:
    server: https://kubernetes.default.svc
    namespace: elk
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
