apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: '55'
spec:
  project: gitops-apps
  source:
    repoURL: https://grafana.github.io/helm-charts
    chart: loki
    targetRevision: 7.0.0
    helm:
      releaseName: loki
      values: |
        deploymentMode: SingleBinary
        loki:
          auth_enabled: false
          commonConfig:
            path_prefix: "/var/loki"
            replication_factor: 1
          storage:
            type: filesystem
          schemaConfig:
            configs:
            - from: '2024-04-01'
              store: tsdb
              object_store: filesystem
              schema: v13
              index:
                prefix: loki_index_
                period: 24h
          limits_config:
            retention_period: 14d
            reject_old_samples: true
            reject_old_samples_max_age: 168h
            volume_enabled: true
          compactor:
            retention_enabled: true
            delete_request_store: filesystem
        singleBinary:
          replicas: 1
          persistence:
            enabled: true
            storageClass: nfs-client
            size: 20Gi
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              memory: 1Gi
        read:
          replicas: 0
        write:
          replicas: 0
        backend:
          replicas: 0
        chunksCache:
          enabled: false
        resultsCache:
          enabled: false
        lokiCanary:
          enabled: false
        test:
          enabled: false
        gateway:
          enabled: true
          basicAuth:
            enabled: true
            username: alloy
            password: architect-business-bot-loki
          ingress:
            enabled: true
            ingressClassName: traefik
            annotations:
              cert-manager.io/cluster-issuer: letsencrypt-production
              external-dns.alpha.kubernetes.io/hostname: loki.api-api-api.com
              external-dns.alpha.kubernetes.io/target: 1a6b03c9-00fc-48fa-af6f-b646c70ce361.cfargotunnel.com
              external-dns.alpha.kubernetes.io/cloudflare-proxied: 'true'
              traefik.ingress.kubernetes.io/router.entrypoints: websecure
              traefik.ingress.kubernetes.io/router.tls: 'true'
            hosts:
            - host: loki.api-api-api.com
              paths:
              - path: "/"
                pathType: Prefix
            tls:
            - secretName: loki-tls-secret
              hosts:
              - loki.api-api-api.com
  destination:
    server: https://kubernetes.default.svc
    namespace: loki
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
