apiVersion: v2
name: arc-controller
version: 0.1.0
type: application
dependencies:
- name: gha-runner-scale-set-controller
  version: "*"
  repository: oci://ghcr.io/actions/actions-runner-controller-charts
