apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: arc-github-token
  namespace: arc-runners
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: arc-github-token
    creationPolicy: Owner
  data:
    - secretKey: github_token
      remoteRef:
        key: "shared/github"
        property: "token"
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: architect-business-bot-ci-telegram
  namespace: arc-runners
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: architect-business-bot-ci-telegram
    creationPolicy: Owner
    template:
      data:
        TELEGRAM_CHAT_ID: "794723616"
  data:
    - secretKey: TELEGRAM_BOT_TOKEN
      remoteRef:
        key: "workload-2/architect-business-bot"
        property: "bot_token"
