vault:
  server:
    dataStorage:
      annotations:
        argocd.argoproj.io/sync-options: Delete=false,Prune=false
        helm.sh/resource-policy: keep
      enabled: true
      size: 5Gi
      storageClass: nfs-client
    ingress:
      enabled: true
      ingressClassName: traefik
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-production
        external-dns.alpha.kubernetes.io/hostname: vault.api-api-api.com
        external-dns.alpha.kubernetes.io/target: 1a6b03c9-00fc-48fa-af6f-b646c70ce361.cfargotunnel.com
      hosts:
      - host: vault.api-api-api.com
        paths: []
      tls:
      - hosts:
        - vault.api-api-api.com
        secretName: vault-tls-secret
  ui:
    enabled: true
