apiVersion: v1
kind: Secret
metadata:
  name: elk-basic-auth
  namespace: elk
type: Opaque
stringData:
  users: |
    elk:$apr1$Y1eeT0xF$Msj66F5kZhoyiKgJheYxm/
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: elk-auth
  namespace: elk
spec:
  basicAuth:
    secret: elk-basic-auth
