apiVersion: v1
kind: Secret
metadata:
  name: elasticsearch-master-certs
  namespace: elk
type: Opaque
stringData:
  ca.crt: |
    disabled
---
apiVersion: v1
kind: Secret
metadata:
  name: elasticsearch-master-credentials
  namespace: elk
type: Opaque
stringData:
  username: elastic
  password: disabled
---
apiVersion: v1
kind: Secret
metadata:
  name: kibana-kibana-es-token
  namespace: elk
type: Opaque
stringData:
  token: disabled
