name: arc-buildkit
namespace: arc-runners

image:
  repository: moby/buildkit
  tag: buildx-stable-1
  pullPolicy: IfNotPresent

persistence:
  storageClassName: local-path
  size: 30Gi

service:
  port: 1234

nodeSelector:
  kubernetes.io/hostname: utility-k3s-worker-2

hostAliases:
  - ip: "10.43.122.186"
    hostnames:
      - harbor.api-api-api.com
