apiVersion: 1
contactPoints:
  - orgId: 1
    name: telegram-platform-alerts
    receivers:
      - uid: telegram-platform-alerts
        type: telegram
        disableResolveMessage: false
        settings:
          chatid: "-5153526231"
          bottoken: $GF_ALERTING_TELEGRAM_BOT_TOKEN
          message: |
            {{ template "telegram.platform.message" . }}
