apiVersion: 1
policies:
  - orgId: 1
    receiver: telegram-platform-alerts
    group_by:
      - grafana_folder
      - alertname
      - cluster
      - namespace
    group_wait: 30s
    group_interval: 5m
    repeat_interval: 4h
    routes:
      - receiver: telegram-platform-alerts
        object_matchers:
          - ["severity", "=", "critical"]
        group_wait: 10s
        group_interval: 2m
        repeat_interval: 1h
      - receiver: telegram-platform-alerts
        object_matchers:
          - ["severity", "=", "warning"]
        group_wait: 30s
        group_interval: 5m
        repeat_interval: 4h
      - receiver: telegram-platform-alerts
        object_matchers:
          - ["severity", "=", "info"]
        group_wait: 2m
        group_interval: 30m
        repeat_interval: 12h
