apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "arc-buildkit.name" . }}
  namespace: {{ include "arc-buildkit.namespace" . }}
  labels:
    {{- include "arc-buildkit.labels" . | nindent 4 }}
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "arc-buildkit.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "arc-buildkit.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.hostAliases }}
      hostAliases:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: buildkitd
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - --addr
            - tcp://0.0.0.0:{{ .Values.service.port }}
          securityContext:
            privileged: true
          ports:
            - name: buildkit
              containerPort: {{ .Values.service.port }}
          livenessProbe:
            tcpSocket:
              port: buildkit
            initialDelaySeconds: 10
            periodSeconds: 20
          readinessProbe:
            tcpSocket:
              port: buildkit
            initialDelaySeconds: 5
            periodSeconds: 10
          volumeMounts:
            - name: cache
              mountPath: /var/lib/buildkit
      volumes:
        - name: cache
          persistentVolumeClaim:
            claimName: {{ include "arc-buildkit.name" . }}-cache
