apiVersion: v1
kind: Service
metadata:
  name: {{ include "arc-buildkit.name" . }}
  namespace: {{ include "arc-buildkit.namespace" . }}
  labels:
    {{- include "arc-buildkit.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: {{ include "arc-buildkit.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: buildkit
      port: {{ .Values.service.port }}
      targetPort: buildkit
