apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: proxmox-exporter
  namespace: proxmox-exporter
spec:
  refreshInterval: "5m"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: proxmox-exporter
    creationPolicy: Owner
  data:
    - secretKey: PVE_USER
      remoteRef:
        key: "shared/proxmox-exporter"
        property: "user"
    - secretKey: PVE_TOKEN_NAME
      remoteRef:
        key: "shared/proxmox-exporter"
        property: "token-name"
    - secretKey: PVE_TOKEN_VALUE
      remoteRef:
        key: "shared/proxmox-exporter"
        property: "token-value"
    - secretKey: PVE_VERIFY_SSL
      remoteRef:
        key: "shared/proxmox-exporter"
        property: "verify-ssl"
