apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - arc
  - argo-workflows
  - cert-manager-config
  - cloudflared
  - external-dns
  - grafana
  - harbor
  - loki
  - minio
  - obsidian-livesync
  - prometheus
  - proxmox-exporter
  - vault
  - vault-store
  - downloader-sloniara-bot
  - elk
