apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: minio-root
  namespace: minio-system
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: minio-root
    creationPolicy: Owner
  data:
    - secretKey: root_user
      remoteRef:
        key: "shared/minio"
        property: "root_user"
    - secretKey: root_password
      remoteRef:
        key: "shared/minio"
        property: "root_password"

