apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana-telegram
  namespace: grafana
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: grafana-telegram
    creationPolicy: Owner
  data:
    - secretKey: botToken
      remoteRef:
        key: "shared/telegram"
        property: "token"
