prometheus:
  alertmanager:
    enabled: false
  prometheus-pushgateway:
    enabled: false
  server:
    extraFlags:
    - web.enable-lifecycle
    - web.enable-remote-write-receiver
    ingress:
      enabled: true
      ingressClassName: traefik
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-production
        external-dns.alpha.kubernetes.io/hostname: prometheus.api-api-api.com
        external-dns.alpha.kubernetes.io/target: a6aaa50f-2590-4179-84f2-d0f18bce0587.cfargotunnel.com
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
        traefik.ingress.kubernetes.io/router.tls: 'true'
      hosts:
      - prometheus.api-api-api.com
      tls:
      - secretName: prometheus-tls-secret
        hosts:
        - prometheus.api-api-api.com
    persistentVolume:
      annotations:
        argocd.argoproj.io/sync-options: Delete=false,Prune=false
        helm.sh/resource-policy: keep
      enabled: true
      size: 20Gi
      storageClass: nfs-client
    retention: 15d
  scrapeConfigs:
    prometheus:
      metric_relabel_configs:
      - target_label: cluster
        replacement: utility-k3s
    kubernetes-api-servers:
      metric_relabel_configs:
      - target_label: cluster
        replacement: utility-k3s
    kubernetes-nodes:
      metric_relabel_configs:
      - target_label: cluster
        replacement: utility-k3s
    kubernetes-nodes-cadvisor:
      metric_relabel_configs:
      - target_label: cluster
        replacement: utility-k3s
    kubernetes-service-endpoints:
      metric_relabel_configs:
      - target_label: cluster
        replacement: utility-k3s
    kubernetes-pods:
      metric_relabel_configs:
      - target_label: cluster
        replacement: utility-k3s
    kubernetes-pods-slow:
      metric_relabel_configs:
      - target_label: cluster
        replacement: utility-k3s
    kubernetes-service-endpoints-slow:
      metric_relabel_configs:
      - target_label: cluster
        replacement: utility-k3s
    kubernetes-services:
      metric_relabel_configs:
      - target_label: cluster
        replacement: utility-k3s
  extraScrapeConfigs: |
    - job_name: pve
      metrics_path: /pve
      params:
        module: [default]
        cluster: ['1']
        node: ['1']
      static_configs:
        - targets:
            - 192.168.1.35
      relabel_configs:
        - source_labels: [__address__]
          target_label: __param_target
        - source_labels: [__param_target]
          target_label: instance
        - target_label: __address__
          replacement: prometheus-pve-exporter.proxmox-exporter.svc.cluster.local:9221

    - job_name: pve-exporter
      static_configs:
        - targets:
            - prometheus-pve-exporter.proxmox-exporter.svc.cluster.local:9221
